-- MySQL Script generated by MySQL Workbench
-- qua 04 out 2023 15:11:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empreendeweek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empreendeweek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empreendeweek` ;
USE `empreendeweek` ;

-- -----------------------------------------------------
-- Table `empreendeweek`.`tipo_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendeweek`.`tipo_atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `interna` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empreendeweek`.`especializacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendeweek`.`especializacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empreendeweek`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendeweek`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `login` VARCHAR(80) NOT NULL,
  `admin` TINYINT NOT NULL,
  `especializacao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `especializacao_id`),
  INDEX `fk_usuario_especializacao_idx` (`especializacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_especializacao`
    FOREIGN KEY (`especializacao_id`)
    REFERENCES `empreendeweek`.`especializacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empreendeweek`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendeweek`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_inicial` DATETIME NOT NULL,
  `data_final` DATETIME NOT NULL,
  `tipo_atividade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_atividade_id`),
  INDEX `fk_atividade_tipo_atividade1_idx` (`tipo_atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividade_tipo_atividade1`
    FOREIGN KEY (`tipo_atividade_id`)
    REFERENCES `empreendeweek`.`tipo_atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empreendeweek`.`usuario_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendeweek`.`usuario_atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_arquivo` VARCHAR(150) NULL,
  `data_upload` DATETIME NULL,
  `arquivo_valido` TINYINT NULL,
  `data_validacao` DATETIME NULL,
  `justificativa` VARCHAR(200) NULL,
  `usuario_id` INT NOT NULL,
  `atividade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `atividade_id`),
  INDEX `fk_usuario_atividade_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_atividade_atividade1_idx` (`atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_atividade_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `empreendeweek`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_atividade_atividade1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `empreendeweek`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
